/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedUsersManagementIndexRouteImport } from './routes/_authenticated/users-management/index'
import { Route as AuthenticatedDaftarVaksinIndexRouteImport } from './routes/_authenticated/daftar-vaksin/index'
import { Route as AuthenticatedDaftarPanenIndexRouteImport } from './routes/_authenticated/daftar-panen/index'
import { Route as AuthenticatedDaftarPakanIndexRouteImport } from './routes/_authenticated/daftar-pakan/index'
import { Route as AuthenticatedDaftarOperasionalIndexRouteImport } from './routes/_authenticated/daftar-operasional/index'
import { Route as AuthenticatedDaftarMortalitasIndexRouteImport } from './routes/_authenticated/daftar-mortalitas/index'
import { Route as AuthenticatedDaftarKandangIndexRouteImport } from './routes/_authenticated/daftar-kandang/index'
import { Route as AuthenticatedDaftarJenisKegiatanIndexRouteImport } from './routes/_authenticated/daftar-jenis-kegiatan/index'
import { Route as AuthenticatedDaftarBiayaIndexRouteImport } from './routes/_authenticated/daftar-biaya/index'
import { Route as AuthenticatedDaftarAyamIndexRouteImport } from './routes/_authenticated/daftar-ayam/index'
import { Route as AuthenticatedUsersManagementCreateRouteImport } from './routes/_authenticated/users-management/create'
import { Route as AuthenticatedUsersManagementIdRouteImport } from './routes/_authenticated/users-management/$id'
import { Route as AuthenticatedDaftarVaksinCreateRouteImport } from './routes/_authenticated/daftar-vaksin/create'
import { Route as AuthenticatedDaftarPanenCreateRouteImport } from './routes/_authenticated/daftar-panen/create'
import { Route as AuthenticatedDaftarPanenIdRouteImport } from './routes/_authenticated/daftar-panen/$id'
import { Route as AuthenticatedDaftarPakanCreateRouteImport } from './routes/_authenticated/daftar-pakan/create'
import { Route as AuthenticatedDaftarOperasionalCreateRouteImport } from './routes/_authenticated/daftar-operasional/create'
import { Route as AuthenticatedDaftarMortalitasCreateRouteImport } from './routes/_authenticated/daftar-mortalitas/create'
import { Route as AuthenticatedDaftarMortalitasIdRouteImport } from './routes/_authenticated/daftar-mortalitas/$id'
import { Route as AuthenticatedDaftarKandangCreateRouteImport } from './routes/_authenticated/daftar-kandang/create'
import { Route as AuthenticatedDaftarKandangIdRouteImport } from './routes/_authenticated/daftar-kandang/$id'
import { Route as AuthenticatedDaftarJenisKegiatanCreateRouteImport } from './routes/_authenticated/daftar-jenis-kegiatan/create'
import { Route as AuthenticatedDaftarBiayaCreateRouteImport } from './routes/_authenticated/daftar-biaya/create'
import { Route as AuthenticatedDaftarBiayaIdRouteImport } from './routes/_authenticated/daftar-biaya/$id'
import { Route as AuthenticatedDaftarAyamCreateRouteImport } from './routes/_authenticated/daftar-ayam/create'
import { Route as AuthenticatedDaftarAyamIdRouteImport } from './routes/_authenticated/daftar-ayam/$id'
import { Route as AuthenticatedUsersManagementIdEditEditRouteImport } from './routes/_authenticated/users-management/$idEdit/edit'
import { Route as AuthenticatedDaftarVaksinIdEditEditRouteImport } from './routes/_authenticated/daftar-vaksin/$idEdit/edit'
import { Route as AuthenticatedDaftarPanenIdEditEditRouteImport } from './routes/_authenticated/daftar-panen/$idEdit/edit'
import { Route as AuthenticatedDaftarPakanIdEditEditRouteImport } from './routes/_authenticated/daftar-pakan/$idEdit/edit'
import { Route as AuthenticatedDaftarOperasionalIdEditEditRouteImport } from './routes/_authenticated/daftar-operasional/$idEdit/edit'
import { Route as AuthenticatedDaftarMortalitasIdEditEditRouteImport } from './routes/_authenticated/daftar-mortalitas/$idEdit/edit'
import { Route as AuthenticatedDaftarKandangIdEditEditRouteImport } from './routes/_authenticated/daftar-kandang/$idEdit/edit'
import { Route as AuthenticatedDaftarJenisKegiatanIdEditEditRouteImport } from './routes/_authenticated/daftar-jenis-kegiatan/$idEdit/edit'
import { Route as AuthenticatedDaftarBiayaIdEditEditRouteImport } from './routes/_authenticated/daftar-biaya/$idEdit/edit'
import { Route as AuthenticatedDaftarAyamIdEditEditRouteImport } from './routes/_authenticated/daftar-ayam/$idEdit/edit'

const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersManagementIndexRoute =
  AuthenticatedUsersManagementIndexRouteImport.update({
    id: '/users-management/',
    path: '/users-management/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarVaksinIndexRoute =
  AuthenticatedDaftarVaksinIndexRouteImport.update({
    id: '/daftar-vaksin/',
    path: '/daftar-vaksin/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarPanenIndexRoute =
  AuthenticatedDaftarPanenIndexRouteImport.update({
    id: '/daftar-panen/',
    path: '/daftar-panen/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarPakanIndexRoute =
  AuthenticatedDaftarPakanIndexRouteImport.update({
    id: '/daftar-pakan/',
    path: '/daftar-pakan/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarOperasionalIndexRoute =
  AuthenticatedDaftarOperasionalIndexRouteImport.update({
    id: '/daftar-operasional/',
    path: '/daftar-operasional/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarMortalitasIndexRoute =
  AuthenticatedDaftarMortalitasIndexRouteImport.update({
    id: '/daftar-mortalitas/',
    path: '/daftar-mortalitas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarKandangIndexRoute =
  AuthenticatedDaftarKandangIndexRouteImport.update({
    id: '/daftar-kandang/',
    path: '/daftar-kandang/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarJenisKegiatanIndexRoute =
  AuthenticatedDaftarJenisKegiatanIndexRouteImport.update({
    id: '/daftar-jenis-kegiatan/',
    path: '/daftar-jenis-kegiatan/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarBiayaIndexRoute =
  AuthenticatedDaftarBiayaIndexRouteImport.update({
    id: '/daftar-biaya/',
    path: '/daftar-biaya/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarAyamIndexRoute =
  AuthenticatedDaftarAyamIndexRouteImport.update({
    id: '/daftar-ayam/',
    path: '/daftar-ayam/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersManagementCreateRoute =
  AuthenticatedUsersManagementCreateRouteImport.update({
    id: '/users-management/create',
    path: '/users-management/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersManagementIdRoute =
  AuthenticatedUsersManagementIdRouteImport.update({
    id: '/users-management/$id',
    path: '/users-management/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarVaksinCreateRoute =
  AuthenticatedDaftarVaksinCreateRouteImport.update({
    id: '/daftar-vaksin/create',
    path: '/daftar-vaksin/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarPanenCreateRoute =
  AuthenticatedDaftarPanenCreateRouteImport.update({
    id: '/daftar-panen/create',
    path: '/daftar-panen/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarPanenIdRoute =
  AuthenticatedDaftarPanenIdRouteImport.update({
    id: '/daftar-panen/$id',
    path: '/daftar-panen/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarPakanCreateRoute =
  AuthenticatedDaftarPakanCreateRouteImport.update({
    id: '/daftar-pakan/create',
    path: '/daftar-pakan/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarOperasionalCreateRoute =
  AuthenticatedDaftarOperasionalCreateRouteImport.update({
    id: '/daftar-operasional/create',
    path: '/daftar-operasional/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarMortalitasCreateRoute =
  AuthenticatedDaftarMortalitasCreateRouteImport.update({
    id: '/daftar-mortalitas/create',
    path: '/daftar-mortalitas/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarMortalitasIdRoute =
  AuthenticatedDaftarMortalitasIdRouteImport.update({
    id: '/daftar-mortalitas/$id',
    path: '/daftar-mortalitas/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarKandangCreateRoute =
  AuthenticatedDaftarKandangCreateRouteImport.update({
    id: '/daftar-kandang/create',
    path: '/daftar-kandang/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarKandangIdRoute =
  AuthenticatedDaftarKandangIdRouteImport.update({
    id: '/daftar-kandang/$id',
    path: '/daftar-kandang/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarJenisKegiatanCreateRoute =
  AuthenticatedDaftarJenisKegiatanCreateRouteImport.update({
    id: '/daftar-jenis-kegiatan/create',
    path: '/daftar-jenis-kegiatan/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarBiayaCreateRoute =
  AuthenticatedDaftarBiayaCreateRouteImport.update({
    id: '/daftar-biaya/create',
    path: '/daftar-biaya/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarBiayaIdRoute =
  AuthenticatedDaftarBiayaIdRouteImport.update({
    id: '/daftar-biaya/$id',
    path: '/daftar-biaya/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarAyamCreateRoute =
  AuthenticatedDaftarAyamCreateRouteImport.update({
    id: '/daftar-ayam/create',
    path: '/daftar-ayam/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarAyamIdRoute =
  AuthenticatedDaftarAyamIdRouteImport.update({
    id: '/daftar-ayam/$id',
    path: '/daftar-ayam/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersManagementIdEditEditRoute =
  AuthenticatedUsersManagementIdEditEditRouteImport.update({
    id: '/users-management/$idEdit/edit',
    path: '/users-management/$idEdit/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarVaksinIdEditEditRoute =
  AuthenticatedDaftarVaksinIdEditEditRouteImport.update({
    id: '/daftar-vaksin/$idEdit/edit',
    path: '/daftar-vaksin/$idEdit/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarPanenIdEditEditRoute =
  AuthenticatedDaftarPanenIdEditEditRouteImport.update({
    id: '/daftar-panen/$idEdit/edit',
    path: '/daftar-panen/$idEdit/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarPakanIdEditEditRoute =
  AuthenticatedDaftarPakanIdEditEditRouteImport.update({
    id: '/daftar-pakan/$idEdit/edit',
    path: '/daftar-pakan/$idEdit/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarOperasionalIdEditEditRoute =
  AuthenticatedDaftarOperasionalIdEditEditRouteImport.update({
    id: '/daftar-operasional/$idEdit/edit',
    path: '/daftar-operasional/$idEdit/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarMortalitasIdEditEditRoute =
  AuthenticatedDaftarMortalitasIdEditEditRouteImport.update({
    id: '/daftar-mortalitas/$idEdit/edit',
    path: '/daftar-mortalitas/$idEdit/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarKandangIdEditEditRoute =
  AuthenticatedDaftarKandangIdEditEditRouteImport.update({
    id: '/daftar-kandang/$idEdit/edit',
    path: '/daftar-kandang/$idEdit/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarJenisKegiatanIdEditEditRoute =
  AuthenticatedDaftarJenisKegiatanIdEditEditRouteImport.update({
    id: '/daftar-jenis-kegiatan/$idEdit/edit',
    path: '/daftar-jenis-kegiatan/$idEdit/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarBiayaIdEditEditRoute =
  AuthenticatedDaftarBiayaIdEditEditRouteImport.update({
    id: '/daftar-biaya/$idEdit/edit',
    path: '/daftar-biaya/$idEdit/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDaftarAyamIdEditEditRoute =
  AuthenticatedDaftarAyamIdEditEditRouteImport.update({
    id: '/daftar-ayam/$idEdit/edit',
    path: '/daftar-ayam/$idEdit/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/daftar-ayam/$id': typeof AuthenticatedDaftarAyamIdRoute
  '/daftar-ayam/create': typeof AuthenticatedDaftarAyamCreateRoute
  '/daftar-biaya/$id': typeof AuthenticatedDaftarBiayaIdRoute
  '/daftar-biaya/create': typeof AuthenticatedDaftarBiayaCreateRoute
  '/daftar-jenis-kegiatan/create': typeof AuthenticatedDaftarJenisKegiatanCreateRoute
  '/daftar-kandang/$id': typeof AuthenticatedDaftarKandangIdRoute
  '/daftar-kandang/create': typeof AuthenticatedDaftarKandangCreateRoute
  '/daftar-mortalitas/$id': typeof AuthenticatedDaftarMortalitasIdRoute
  '/daftar-mortalitas/create': typeof AuthenticatedDaftarMortalitasCreateRoute
  '/daftar-operasional/create': typeof AuthenticatedDaftarOperasionalCreateRoute
  '/daftar-pakan/create': typeof AuthenticatedDaftarPakanCreateRoute
  '/daftar-panen/$id': typeof AuthenticatedDaftarPanenIdRoute
  '/daftar-panen/create': typeof AuthenticatedDaftarPanenCreateRoute
  '/daftar-vaksin/create': typeof AuthenticatedDaftarVaksinCreateRoute
  '/users-management/$id': typeof AuthenticatedUsersManagementIdRoute
  '/users-management/create': typeof AuthenticatedUsersManagementCreateRoute
  '/daftar-ayam': typeof AuthenticatedDaftarAyamIndexRoute
  '/daftar-biaya': typeof AuthenticatedDaftarBiayaIndexRoute
  '/daftar-jenis-kegiatan': typeof AuthenticatedDaftarJenisKegiatanIndexRoute
  '/daftar-kandang': typeof AuthenticatedDaftarKandangIndexRoute
  '/daftar-mortalitas': typeof AuthenticatedDaftarMortalitasIndexRoute
  '/daftar-operasional': typeof AuthenticatedDaftarOperasionalIndexRoute
  '/daftar-pakan': typeof AuthenticatedDaftarPakanIndexRoute
  '/daftar-panen': typeof AuthenticatedDaftarPanenIndexRoute
  '/daftar-vaksin': typeof AuthenticatedDaftarVaksinIndexRoute
  '/users-management': typeof AuthenticatedUsersManagementIndexRoute
  '/daftar-ayam/$idEdit/edit': typeof AuthenticatedDaftarAyamIdEditEditRoute
  '/daftar-biaya/$idEdit/edit': typeof AuthenticatedDaftarBiayaIdEditEditRoute
  '/daftar-jenis-kegiatan/$idEdit/edit': typeof AuthenticatedDaftarJenisKegiatanIdEditEditRoute
  '/daftar-kandang/$idEdit/edit': typeof AuthenticatedDaftarKandangIdEditEditRoute
  '/daftar-mortalitas/$idEdit/edit': typeof AuthenticatedDaftarMortalitasIdEditEditRoute
  '/daftar-operasional/$idEdit/edit': typeof AuthenticatedDaftarOperasionalIdEditEditRoute
  '/daftar-pakan/$idEdit/edit': typeof AuthenticatedDaftarPakanIdEditEditRoute
  '/daftar-panen/$idEdit/edit': typeof AuthenticatedDaftarPanenIdEditEditRoute
  '/daftar-vaksin/$idEdit/edit': typeof AuthenticatedDaftarVaksinIdEditEditRoute
  '/users-management/$idEdit/edit': typeof AuthenticatedUsersManagementIdEditEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/daftar-ayam/$id': typeof AuthenticatedDaftarAyamIdRoute
  '/daftar-ayam/create': typeof AuthenticatedDaftarAyamCreateRoute
  '/daftar-biaya/$id': typeof AuthenticatedDaftarBiayaIdRoute
  '/daftar-biaya/create': typeof AuthenticatedDaftarBiayaCreateRoute
  '/daftar-jenis-kegiatan/create': typeof AuthenticatedDaftarJenisKegiatanCreateRoute
  '/daftar-kandang/$id': typeof AuthenticatedDaftarKandangIdRoute
  '/daftar-kandang/create': typeof AuthenticatedDaftarKandangCreateRoute
  '/daftar-mortalitas/$id': typeof AuthenticatedDaftarMortalitasIdRoute
  '/daftar-mortalitas/create': typeof AuthenticatedDaftarMortalitasCreateRoute
  '/daftar-operasional/create': typeof AuthenticatedDaftarOperasionalCreateRoute
  '/daftar-pakan/create': typeof AuthenticatedDaftarPakanCreateRoute
  '/daftar-panen/$id': typeof AuthenticatedDaftarPanenIdRoute
  '/daftar-panen/create': typeof AuthenticatedDaftarPanenCreateRoute
  '/daftar-vaksin/create': typeof AuthenticatedDaftarVaksinCreateRoute
  '/users-management/$id': typeof AuthenticatedUsersManagementIdRoute
  '/users-management/create': typeof AuthenticatedUsersManagementCreateRoute
  '/daftar-ayam': typeof AuthenticatedDaftarAyamIndexRoute
  '/daftar-biaya': typeof AuthenticatedDaftarBiayaIndexRoute
  '/daftar-jenis-kegiatan': typeof AuthenticatedDaftarJenisKegiatanIndexRoute
  '/daftar-kandang': typeof AuthenticatedDaftarKandangIndexRoute
  '/daftar-mortalitas': typeof AuthenticatedDaftarMortalitasIndexRoute
  '/daftar-operasional': typeof AuthenticatedDaftarOperasionalIndexRoute
  '/daftar-pakan': typeof AuthenticatedDaftarPakanIndexRoute
  '/daftar-panen': typeof AuthenticatedDaftarPanenIndexRoute
  '/daftar-vaksin': typeof AuthenticatedDaftarVaksinIndexRoute
  '/users-management': typeof AuthenticatedUsersManagementIndexRoute
  '/daftar-ayam/$idEdit/edit': typeof AuthenticatedDaftarAyamIdEditEditRoute
  '/daftar-biaya/$idEdit/edit': typeof AuthenticatedDaftarBiayaIdEditEditRoute
  '/daftar-jenis-kegiatan/$idEdit/edit': typeof AuthenticatedDaftarJenisKegiatanIdEditEditRoute
  '/daftar-kandang/$idEdit/edit': typeof AuthenticatedDaftarKandangIdEditEditRoute
  '/daftar-mortalitas/$idEdit/edit': typeof AuthenticatedDaftarMortalitasIdEditEditRoute
  '/daftar-operasional/$idEdit/edit': typeof AuthenticatedDaftarOperasionalIdEditEditRoute
  '/daftar-pakan/$idEdit/edit': typeof AuthenticatedDaftarPakanIdEditEditRoute
  '/daftar-panen/$idEdit/edit': typeof AuthenticatedDaftarPanenIdEditEditRoute
  '/daftar-vaksin/$idEdit/edit': typeof AuthenticatedDaftarVaksinIdEditEditRoute
  '/users-management/$idEdit/edit': typeof AuthenticatedUsersManagementIdEditEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/daftar-ayam/$id': typeof AuthenticatedDaftarAyamIdRoute
  '/_authenticated/daftar-ayam/create': typeof AuthenticatedDaftarAyamCreateRoute
  '/_authenticated/daftar-biaya/$id': typeof AuthenticatedDaftarBiayaIdRoute
  '/_authenticated/daftar-biaya/create': typeof AuthenticatedDaftarBiayaCreateRoute
  '/_authenticated/daftar-jenis-kegiatan/create': typeof AuthenticatedDaftarJenisKegiatanCreateRoute
  '/_authenticated/daftar-kandang/$id': typeof AuthenticatedDaftarKandangIdRoute
  '/_authenticated/daftar-kandang/create': typeof AuthenticatedDaftarKandangCreateRoute
  '/_authenticated/daftar-mortalitas/$id': typeof AuthenticatedDaftarMortalitasIdRoute
  '/_authenticated/daftar-mortalitas/create': typeof AuthenticatedDaftarMortalitasCreateRoute
  '/_authenticated/daftar-operasional/create': typeof AuthenticatedDaftarOperasionalCreateRoute
  '/_authenticated/daftar-pakan/create': typeof AuthenticatedDaftarPakanCreateRoute
  '/_authenticated/daftar-panen/$id': typeof AuthenticatedDaftarPanenIdRoute
  '/_authenticated/daftar-panen/create': typeof AuthenticatedDaftarPanenCreateRoute
  '/_authenticated/daftar-vaksin/create': typeof AuthenticatedDaftarVaksinCreateRoute
  '/_authenticated/users-management/$id': typeof AuthenticatedUsersManagementIdRoute
  '/_authenticated/users-management/create': typeof AuthenticatedUsersManagementCreateRoute
  '/_authenticated/daftar-ayam/': typeof AuthenticatedDaftarAyamIndexRoute
  '/_authenticated/daftar-biaya/': typeof AuthenticatedDaftarBiayaIndexRoute
  '/_authenticated/daftar-jenis-kegiatan/': typeof AuthenticatedDaftarJenisKegiatanIndexRoute
  '/_authenticated/daftar-kandang/': typeof AuthenticatedDaftarKandangIndexRoute
  '/_authenticated/daftar-mortalitas/': typeof AuthenticatedDaftarMortalitasIndexRoute
  '/_authenticated/daftar-operasional/': typeof AuthenticatedDaftarOperasionalIndexRoute
  '/_authenticated/daftar-pakan/': typeof AuthenticatedDaftarPakanIndexRoute
  '/_authenticated/daftar-panen/': typeof AuthenticatedDaftarPanenIndexRoute
  '/_authenticated/daftar-vaksin/': typeof AuthenticatedDaftarVaksinIndexRoute
  '/_authenticated/users-management/': typeof AuthenticatedUsersManagementIndexRoute
  '/_authenticated/daftar-ayam/$idEdit/edit': typeof AuthenticatedDaftarAyamIdEditEditRoute
  '/_authenticated/daftar-biaya/$idEdit/edit': typeof AuthenticatedDaftarBiayaIdEditEditRoute
  '/_authenticated/daftar-jenis-kegiatan/$idEdit/edit': typeof AuthenticatedDaftarJenisKegiatanIdEditEditRoute
  '/_authenticated/daftar-kandang/$idEdit/edit': typeof AuthenticatedDaftarKandangIdEditEditRoute
  '/_authenticated/daftar-mortalitas/$idEdit/edit': typeof AuthenticatedDaftarMortalitasIdEditEditRoute
  '/_authenticated/daftar-operasional/$idEdit/edit': typeof AuthenticatedDaftarOperasionalIdEditEditRoute
  '/_authenticated/daftar-pakan/$idEdit/edit': typeof AuthenticatedDaftarPakanIdEditEditRoute
  '/_authenticated/daftar-panen/$idEdit/edit': typeof AuthenticatedDaftarPanenIdEditEditRoute
  '/_authenticated/daftar-vaksin/$idEdit/edit': typeof AuthenticatedDaftarVaksinIdEditEditRoute
  '/_authenticated/users-management/$idEdit/edit': typeof AuthenticatedUsersManagementIdEditEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/dashboard'
    | '/profile'
    | '/daftar-ayam/$id'
    | '/daftar-ayam/create'
    | '/daftar-biaya/$id'
    | '/daftar-biaya/create'
    | '/daftar-jenis-kegiatan/create'
    | '/daftar-kandang/$id'
    | '/daftar-kandang/create'
    | '/daftar-mortalitas/$id'
    | '/daftar-mortalitas/create'
    | '/daftar-operasional/create'
    | '/daftar-pakan/create'
    | '/daftar-panen/$id'
    | '/daftar-panen/create'
    | '/daftar-vaksin/create'
    | '/users-management/$id'
    | '/users-management/create'
    | '/daftar-ayam'
    | '/daftar-biaya'
    | '/daftar-jenis-kegiatan'
    | '/daftar-kandang'
    | '/daftar-mortalitas'
    | '/daftar-operasional'
    | '/daftar-pakan'
    | '/daftar-panen'
    | '/daftar-vaksin'
    | '/users-management'
    | '/daftar-ayam/$idEdit/edit'
    | '/daftar-biaya/$idEdit/edit'
    | '/daftar-jenis-kegiatan/$idEdit/edit'
    | '/daftar-kandang/$idEdit/edit'
    | '/daftar-mortalitas/$idEdit/edit'
    | '/daftar-operasional/$idEdit/edit'
    | '/daftar-pakan/$idEdit/edit'
    | '/daftar-panen/$idEdit/edit'
    | '/daftar-vaksin/$idEdit/edit'
    | '/users-management/$idEdit/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/dashboard'
    | '/profile'
    | '/daftar-ayam/$id'
    | '/daftar-ayam/create'
    | '/daftar-biaya/$id'
    | '/daftar-biaya/create'
    | '/daftar-jenis-kegiatan/create'
    | '/daftar-kandang/$id'
    | '/daftar-kandang/create'
    | '/daftar-mortalitas/$id'
    | '/daftar-mortalitas/create'
    | '/daftar-operasional/create'
    | '/daftar-pakan/create'
    | '/daftar-panen/$id'
    | '/daftar-panen/create'
    | '/daftar-vaksin/create'
    | '/users-management/$id'
    | '/users-management/create'
    | '/daftar-ayam'
    | '/daftar-biaya'
    | '/daftar-jenis-kegiatan'
    | '/daftar-kandang'
    | '/daftar-mortalitas'
    | '/daftar-operasional'
    | '/daftar-pakan'
    | '/daftar-panen'
    | '/daftar-vaksin'
    | '/users-management'
    | '/daftar-ayam/$idEdit/edit'
    | '/daftar-biaya/$idEdit/edit'
    | '/daftar-jenis-kegiatan/$idEdit/edit'
    | '/daftar-kandang/$idEdit/edit'
    | '/daftar-mortalitas/$idEdit/edit'
    | '/daftar-operasional/$idEdit/edit'
    | '/daftar-pakan/$idEdit/edit'
    | '/daftar-panen/$idEdit/edit'
    | '/daftar-vaksin/$idEdit/edit'
    | '/users-management/$idEdit/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/forgot-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/daftar-ayam/$id'
    | '/_authenticated/daftar-ayam/create'
    | '/_authenticated/daftar-biaya/$id'
    | '/_authenticated/daftar-biaya/create'
    | '/_authenticated/daftar-jenis-kegiatan/create'
    | '/_authenticated/daftar-kandang/$id'
    | '/_authenticated/daftar-kandang/create'
    | '/_authenticated/daftar-mortalitas/$id'
    | '/_authenticated/daftar-mortalitas/create'
    | '/_authenticated/daftar-operasional/create'
    | '/_authenticated/daftar-pakan/create'
    | '/_authenticated/daftar-panen/$id'
    | '/_authenticated/daftar-panen/create'
    | '/_authenticated/daftar-vaksin/create'
    | '/_authenticated/users-management/$id'
    | '/_authenticated/users-management/create'
    | '/_authenticated/daftar-ayam/'
    | '/_authenticated/daftar-biaya/'
    | '/_authenticated/daftar-jenis-kegiatan/'
    | '/_authenticated/daftar-kandang/'
    | '/_authenticated/daftar-mortalitas/'
    | '/_authenticated/daftar-operasional/'
    | '/_authenticated/daftar-pakan/'
    | '/_authenticated/daftar-panen/'
    | '/_authenticated/daftar-vaksin/'
    | '/_authenticated/users-management/'
    | '/_authenticated/daftar-ayam/$idEdit/edit'
    | '/_authenticated/daftar-biaya/$idEdit/edit'
    | '/_authenticated/daftar-jenis-kegiatan/$idEdit/edit'
    | '/_authenticated/daftar-kandang/$idEdit/edit'
    | '/_authenticated/daftar-mortalitas/$idEdit/edit'
    | '/_authenticated/daftar-operasional/$idEdit/edit'
    | '/_authenticated/daftar-pakan/$idEdit/edit'
    | '/_authenticated/daftar-panen/$idEdit/edit'
    | '/_authenticated/daftar-vaksin/$idEdit/edit'
    | '/_authenticated/users-management/$idEdit/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users-management/': {
      id: '/_authenticated/users-management/'
      path: '/users-management'
      fullPath: '/users-management'
      preLoaderRoute: typeof AuthenticatedUsersManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-vaksin/': {
      id: '/_authenticated/daftar-vaksin/'
      path: '/daftar-vaksin'
      fullPath: '/daftar-vaksin'
      preLoaderRoute: typeof AuthenticatedDaftarVaksinIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-panen/': {
      id: '/_authenticated/daftar-panen/'
      path: '/daftar-panen'
      fullPath: '/daftar-panen'
      preLoaderRoute: typeof AuthenticatedDaftarPanenIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-pakan/': {
      id: '/_authenticated/daftar-pakan/'
      path: '/daftar-pakan'
      fullPath: '/daftar-pakan'
      preLoaderRoute: typeof AuthenticatedDaftarPakanIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-operasional/': {
      id: '/_authenticated/daftar-operasional/'
      path: '/daftar-operasional'
      fullPath: '/daftar-operasional'
      preLoaderRoute: typeof AuthenticatedDaftarOperasionalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-mortalitas/': {
      id: '/_authenticated/daftar-mortalitas/'
      path: '/daftar-mortalitas'
      fullPath: '/daftar-mortalitas'
      preLoaderRoute: typeof AuthenticatedDaftarMortalitasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-kandang/': {
      id: '/_authenticated/daftar-kandang/'
      path: '/daftar-kandang'
      fullPath: '/daftar-kandang'
      preLoaderRoute: typeof AuthenticatedDaftarKandangIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-jenis-kegiatan/': {
      id: '/_authenticated/daftar-jenis-kegiatan/'
      path: '/daftar-jenis-kegiatan'
      fullPath: '/daftar-jenis-kegiatan'
      preLoaderRoute: typeof AuthenticatedDaftarJenisKegiatanIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-biaya/': {
      id: '/_authenticated/daftar-biaya/'
      path: '/daftar-biaya'
      fullPath: '/daftar-biaya'
      preLoaderRoute: typeof AuthenticatedDaftarBiayaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-ayam/': {
      id: '/_authenticated/daftar-ayam/'
      path: '/daftar-ayam'
      fullPath: '/daftar-ayam'
      preLoaderRoute: typeof AuthenticatedDaftarAyamIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users-management/create': {
      id: '/_authenticated/users-management/create'
      path: '/users-management/create'
      fullPath: '/users-management/create'
      preLoaderRoute: typeof AuthenticatedUsersManagementCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users-management/$id': {
      id: '/_authenticated/users-management/$id'
      path: '/users-management/$id'
      fullPath: '/users-management/$id'
      preLoaderRoute: typeof AuthenticatedUsersManagementIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-vaksin/create': {
      id: '/_authenticated/daftar-vaksin/create'
      path: '/daftar-vaksin/create'
      fullPath: '/daftar-vaksin/create'
      preLoaderRoute: typeof AuthenticatedDaftarVaksinCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-panen/create': {
      id: '/_authenticated/daftar-panen/create'
      path: '/daftar-panen/create'
      fullPath: '/daftar-panen/create'
      preLoaderRoute: typeof AuthenticatedDaftarPanenCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-panen/$id': {
      id: '/_authenticated/daftar-panen/$id'
      path: '/daftar-panen/$id'
      fullPath: '/daftar-panen/$id'
      preLoaderRoute: typeof AuthenticatedDaftarPanenIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-pakan/create': {
      id: '/_authenticated/daftar-pakan/create'
      path: '/daftar-pakan/create'
      fullPath: '/daftar-pakan/create'
      preLoaderRoute: typeof AuthenticatedDaftarPakanCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-operasional/create': {
      id: '/_authenticated/daftar-operasional/create'
      path: '/daftar-operasional/create'
      fullPath: '/daftar-operasional/create'
      preLoaderRoute: typeof AuthenticatedDaftarOperasionalCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-mortalitas/create': {
      id: '/_authenticated/daftar-mortalitas/create'
      path: '/daftar-mortalitas/create'
      fullPath: '/daftar-mortalitas/create'
      preLoaderRoute: typeof AuthenticatedDaftarMortalitasCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-mortalitas/$id': {
      id: '/_authenticated/daftar-mortalitas/$id'
      path: '/daftar-mortalitas/$id'
      fullPath: '/daftar-mortalitas/$id'
      preLoaderRoute: typeof AuthenticatedDaftarMortalitasIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-kandang/create': {
      id: '/_authenticated/daftar-kandang/create'
      path: '/daftar-kandang/create'
      fullPath: '/daftar-kandang/create'
      preLoaderRoute: typeof AuthenticatedDaftarKandangCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-kandang/$id': {
      id: '/_authenticated/daftar-kandang/$id'
      path: '/daftar-kandang/$id'
      fullPath: '/daftar-kandang/$id'
      preLoaderRoute: typeof AuthenticatedDaftarKandangIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-jenis-kegiatan/create': {
      id: '/_authenticated/daftar-jenis-kegiatan/create'
      path: '/daftar-jenis-kegiatan/create'
      fullPath: '/daftar-jenis-kegiatan/create'
      preLoaderRoute: typeof AuthenticatedDaftarJenisKegiatanCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-biaya/create': {
      id: '/_authenticated/daftar-biaya/create'
      path: '/daftar-biaya/create'
      fullPath: '/daftar-biaya/create'
      preLoaderRoute: typeof AuthenticatedDaftarBiayaCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-biaya/$id': {
      id: '/_authenticated/daftar-biaya/$id'
      path: '/daftar-biaya/$id'
      fullPath: '/daftar-biaya/$id'
      preLoaderRoute: typeof AuthenticatedDaftarBiayaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-ayam/create': {
      id: '/_authenticated/daftar-ayam/create'
      path: '/daftar-ayam/create'
      fullPath: '/daftar-ayam/create'
      preLoaderRoute: typeof AuthenticatedDaftarAyamCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-ayam/$id': {
      id: '/_authenticated/daftar-ayam/$id'
      path: '/daftar-ayam/$id'
      fullPath: '/daftar-ayam/$id'
      preLoaderRoute: typeof AuthenticatedDaftarAyamIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users-management/$idEdit/edit': {
      id: '/_authenticated/users-management/$idEdit/edit'
      path: '/users-management/$idEdit/edit'
      fullPath: '/users-management/$idEdit/edit'
      preLoaderRoute: typeof AuthenticatedUsersManagementIdEditEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-vaksin/$idEdit/edit': {
      id: '/_authenticated/daftar-vaksin/$idEdit/edit'
      path: '/daftar-vaksin/$idEdit/edit'
      fullPath: '/daftar-vaksin/$idEdit/edit'
      preLoaderRoute: typeof AuthenticatedDaftarVaksinIdEditEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-panen/$idEdit/edit': {
      id: '/_authenticated/daftar-panen/$idEdit/edit'
      path: '/daftar-panen/$idEdit/edit'
      fullPath: '/daftar-panen/$idEdit/edit'
      preLoaderRoute: typeof AuthenticatedDaftarPanenIdEditEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-pakan/$idEdit/edit': {
      id: '/_authenticated/daftar-pakan/$idEdit/edit'
      path: '/daftar-pakan/$idEdit/edit'
      fullPath: '/daftar-pakan/$idEdit/edit'
      preLoaderRoute: typeof AuthenticatedDaftarPakanIdEditEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-operasional/$idEdit/edit': {
      id: '/_authenticated/daftar-operasional/$idEdit/edit'
      path: '/daftar-operasional/$idEdit/edit'
      fullPath: '/daftar-operasional/$idEdit/edit'
      preLoaderRoute: typeof AuthenticatedDaftarOperasionalIdEditEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-mortalitas/$idEdit/edit': {
      id: '/_authenticated/daftar-mortalitas/$idEdit/edit'
      path: '/daftar-mortalitas/$idEdit/edit'
      fullPath: '/daftar-mortalitas/$idEdit/edit'
      preLoaderRoute: typeof AuthenticatedDaftarMortalitasIdEditEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-kandang/$idEdit/edit': {
      id: '/_authenticated/daftar-kandang/$idEdit/edit'
      path: '/daftar-kandang/$idEdit/edit'
      fullPath: '/daftar-kandang/$idEdit/edit'
      preLoaderRoute: typeof AuthenticatedDaftarKandangIdEditEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-jenis-kegiatan/$idEdit/edit': {
      id: '/_authenticated/daftar-jenis-kegiatan/$idEdit/edit'
      path: '/daftar-jenis-kegiatan/$idEdit/edit'
      fullPath: '/daftar-jenis-kegiatan/$idEdit/edit'
      preLoaderRoute: typeof AuthenticatedDaftarJenisKegiatanIdEditEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-biaya/$idEdit/edit': {
      id: '/_authenticated/daftar-biaya/$idEdit/edit'
      path: '/daftar-biaya/$idEdit/edit'
      fullPath: '/daftar-biaya/$idEdit/edit'
      preLoaderRoute: typeof AuthenticatedDaftarBiayaIdEditEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daftar-ayam/$idEdit/edit': {
      id: '/_authenticated/daftar-ayam/$idEdit/edit'
      path: '/daftar-ayam/$idEdit/edit'
      fullPath: '/daftar-ayam/$idEdit/edit'
      preLoaderRoute: typeof AuthenticatedDaftarAyamIdEditEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedDaftarAyamIdRoute: typeof AuthenticatedDaftarAyamIdRoute
  AuthenticatedDaftarAyamCreateRoute: typeof AuthenticatedDaftarAyamCreateRoute
  AuthenticatedDaftarBiayaIdRoute: typeof AuthenticatedDaftarBiayaIdRoute
  AuthenticatedDaftarBiayaCreateRoute: typeof AuthenticatedDaftarBiayaCreateRoute
  AuthenticatedDaftarJenisKegiatanCreateRoute: typeof AuthenticatedDaftarJenisKegiatanCreateRoute
  AuthenticatedDaftarKandangIdRoute: typeof AuthenticatedDaftarKandangIdRoute
  AuthenticatedDaftarKandangCreateRoute: typeof AuthenticatedDaftarKandangCreateRoute
  AuthenticatedDaftarMortalitasIdRoute: typeof AuthenticatedDaftarMortalitasIdRoute
  AuthenticatedDaftarMortalitasCreateRoute: typeof AuthenticatedDaftarMortalitasCreateRoute
  AuthenticatedDaftarOperasionalCreateRoute: typeof AuthenticatedDaftarOperasionalCreateRoute
  AuthenticatedDaftarPakanCreateRoute: typeof AuthenticatedDaftarPakanCreateRoute
  AuthenticatedDaftarPanenIdRoute: typeof AuthenticatedDaftarPanenIdRoute
  AuthenticatedDaftarPanenCreateRoute: typeof AuthenticatedDaftarPanenCreateRoute
  AuthenticatedDaftarVaksinCreateRoute: typeof AuthenticatedDaftarVaksinCreateRoute
  AuthenticatedUsersManagementIdRoute: typeof AuthenticatedUsersManagementIdRoute
  AuthenticatedUsersManagementCreateRoute: typeof AuthenticatedUsersManagementCreateRoute
  AuthenticatedDaftarAyamIndexRoute: typeof AuthenticatedDaftarAyamIndexRoute
  AuthenticatedDaftarBiayaIndexRoute: typeof AuthenticatedDaftarBiayaIndexRoute
  AuthenticatedDaftarJenisKegiatanIndexRoute: typeof AuthenticatedDaftarJenisKegiatanIndexRoute
  AuthenticatedDaftarKandangIndexRoute: typeof AuthenticatedDaftarKandangIndexRoute
  AuthenticatedDaftarMortalitasIndexRoute: typeof AuthenticatedDaftarMortalitasIndexRoute
  AuthenticatedDaftarOperasionalIndexRoute: typeof AuthenticatedDaftarOperasionalIndexRoute
  AuthenticatedDaftarPakanIndexRoute: typeof AuthenticatedDaftarPakanIndexRoute
  AuthenticatedDaftarPanenIndexRoute: typeof AuthenticatedDaftarPanenIndexRoute
  AuthenticatedDaftarVaksinIndexRoute: typeof AuthenticatedDaftarVaksinIndexRoute
  AuthenticatedUsersManagementIndexRoute: typeof AuthenticatedUsersManagementIndexRoute
  AuthenticatedDaftarAyamIdEditEditRoute: typeof AuthenticatedDaftarAyamIdEditEditRoute
  AuthenticatedDaftarBiayaIdEditEditRoute: typeof AuthenticatedDaftarBiayaIdEditEditRoute
  AuthenticatedDaftarJenisKegiatanIdEditEditRoute: typeof AuthenticatedDaftarJenisKegiatanIdEditEditRoute
  AuthenticatedDaftarKandangIdEditEditRoute: typeof AuthenticatedDaftarKandangIdEditEditRoute
  AuthenticatedDaftarMortalitasIdEditEditRoute: typeof AuthenticatedDaftarMortalitasIdEditEditRoute
  AuthenticatedDaftarOperasionalIdEditEditRoute: typeof AuthenticatedDaftarOperasionalIdEditEditRoute
  AuthenticatedDaftarPakanIdEditEditRoute: typeof AuthenticatedDaftarPakanIdEditEditRoute
  AuthenticatedDaftarPanenIdEditEditRoute: typeof AuthenticatedDaftarPanenIdEditEditRoute
  AuthenticatedDaftarVaksinIdEditEditRoute: typeof AuthenticatedDaftarVaksinIdEditEditRoute
  AuthenticatedUsersManagementIdEditEditRoute: typeof AuthenticatedUsersManagementIdEditEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedDaftarAyamIdRoute: AuthenticatedDaftarAyamIdRoute,
  AuthenticatedDaftarAyamCreateRoute: AuthenticatedDaftarAyamCreateRoute,
  AuthenticatedDaftarBiayaIdRoute: AuthenticatedDaftarBiayaIdRoute,
  AuthenticatedDaftarBiayaCreateRoute: AuthenticatedDaftarBiayaCreateRoute,
  AuthenticatedDaftarJenisKegiatanCreateRoute:
    AuthenticatedDaftarJenisKegiatanCreateRoute,
  AuthenticatedDaftarKandangIdRoute: AuthenticatedDaftarKandangIdRoute,
  AuthenticatedDaftarKandangCreateRoute: AuthenticatedDaftarKandangCreateRoute,
  AuthenticatedDaftarMortalitasIdRoute: AuthenticatedDaftarMortalitasIdRoute,
  AuthenticatedDaftarMortalitasCreateRoute:
    AuthenticatedDaftarMortalitasCreateRoute,
  AuthenticatedDaftarOperasionalCreateRoute:
    AuthenticatedDaftarOperasionalCreateRoute,
  AuthenticatedDaftarPakanCreateRoute: AuthenticatedDaftarPakanCreateRoute,
  AuthenticatedDaftarPanenIdRoute: AuthenticatedDaftarPanenIdRoute,
  AuthenticatedDaftarPanenCreateRoute: AuthenticatedDaftarPanenCreateRoute,
  AuthenticatedDaftarVaksinCreateRoute: AuthenticatedDaftarVaksinCreateRoute,
  AuthenticatedUsersManagementIdRoute: AuthenticatedUsersManagementIdRoute,
  AuthenticatedUsersManagementCreateRoute:
    AuthenticatedUsersManagementCreateRoute,
  AuthenticatedDaftarAyamIndexRoute: AuthenticatedDaftarAyamIndexRoute,
  AuthenticatedDaftarBiayaIndexRoute: AuthenticatedDaftarBiayaIndexRoute,
  AuthenticatedDaftarJenisKegiatanIndexRoute:
    AuthenticatedDaftarJenisKegiatanIndexRoute,
  AuthenticatedDaftarKandangIndexRoute: AuthenticatedDaftarKandangIndexRoute,
  AuthenticatedDaftarMortalitasIndexRoute:
    AuthenticatedDaftarMortalitasIndexRoute,
  AuthenticatedDaftarOperasionalIndexRoute:
    AuthenticatedDaftarOperasionalIndexRoute,
  AuthenticatedDaftarPakanIndexRoute: AuthenticatedDaftarPakanIndexRoute,
  AuthenticatedDaftarPanenIndexRoute: AuthenticatedDaftarPanenIndexRoute,
  AuthenticatedDaftarVaksinIndexRoute: AuthenticatedDaftarVaksinIndexRoute,
  AuthenticatedUsersManagementIndexRoute:
    AuthenticatedUsersManagementIndexRoute,
  AuthenticatedDaftarAyamIdEditEditRoute:
    AuthenticatedDaftarAyamIdEditEditRoute,
  AuthenticatedDaftarBiayaIdEditEditRoute:
    AuthenticatedDaftarBiayaIdEditEditRoute,
  AuthenticatedDaftarJenisKegiatanIdEditEditRoute:
    AuthenticatedDaftarJenisKegiatanIdEditEditRoute,
  AuthenticatedDaftarKandangIdEditEditRoute:
    AuthenticatedDaftarKandangIdEditEditRoute,
  AuthenticatedDaftarMortalitasIdEditEditRoute:
    AuthenticatedDaftarMortalitasIdEditEditRoute,
  AuthenticatedDaftarOperasionalIdEditEditRoute:
    AuthenticatedDaftarOperasionalIdEditEditRoute,
  AuthenticatedDaftarPakanIdEditEditRoute:
    AuthenticatedDaftarPakanIdEditEditRoute,
  AuthenticatedDaftarPanenIdEditEditRoute:
    AuthenticatedDaftarPanenIdEditEditRoute,
  AuthenticatedDaftarVaksinIdEditEditRoute:
    AuthenticatedDaftarVaksinIdEditEditRoute,
  AuthenticatedUsersManagementIdEditEditRoute:
    AuthenticatedUsersManagementIdEditEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
